### PR TITLE
yiranw8: added reducerList with count, added count col on ServerList page

### PR DESCRIPTION
**Pull request by erin-yiran-wang**
[9b81132](https://github.com/cs340-illinois/1989-shared-middleware/pull/25/commits/9b8113207f1862c840567176a278703d4e9c4756)added reducerList.html
app.py:
- added GET route to reducerList

reducers.html:
- added reducers.html in the templates folder that generates the page for reducers with id, URL, and author

index.html:
- added reducerList button to the main index
servers.html:
- added reducerList button on servers page as well

[dae9493](https://github.com/cs340-illinois/1989-shared-middleware/pull/25/commits/dae94939c7760a45fd38f3cf5639a425f66cb578)added count of calls on MMG Servers page
app.py
- added "count" attribute for each mmg_server (set to 0 when added the MMG, then increment when make Mosaic is called)
servers.html
- added "Count" Column 

[8623639](https://github.com/cs340-illinois/1989-shared-middleware/pull/25/commits/86236393edd5e61d15549ec847982cb2b2b2b693) added count for mmg servers and reducers
reducers.html
- added count column
Mosaics.Worker.py
- incremented count for mmg servers and reducers at the end of awaitReducer and awaitMMG functions

### CODE REVIEW

**Comment by kcoopermiller** [comment]
Hey! I was also just working on issue #20 and wanted to share my thoughts about how I approached incrementing the number of calls :)

I think incrementing the `count` value for each MMG (and possibly Reducers) inside their respective `awaitMMG` and `awaitReducer` functions in the `MosaicWorker.py` file is a more accurate approach than doing it in the `/makeMosaic` route of `app.py` 

So instead of 
```python
# app.py
async def POST_makeMosaic():
        ....
        for id in mmg_servers:
            worker.addMMG( mmg_servers[id] )
            mmg_servers[id]['count'] +=1
```
I did
```python
# MosaicWorker.py
async def awaitMMG(self, mmg):
        ...
        self.mmgCompleted = self.mmgCompleted + 1
        mmg["count"] += 1
```


The `/makeMosaic` route is responsible for initializing the mosaic creation process and setting up the `MosaicWorker` with the necessary parameters; however, I don't think it directly calls the MMGs or Reducers. Which I believe could be a problem because even if there are any errors or issues during the mosaic generation process, the count would have already been incremented.

Also, if I'm understanding everything correctly, I believe that if you increment the `count` value in the `/makeMosaic` route, you are making an assumption about the number of times each MMG or Reducer will be called during the mosaic creation process.


Not sure if any of these changes matter too much lol, I just thought I'd comment because I was also working on this issue. Everything else LGTM 👍

**Comment by erin-yiran-wang** [comment]
Hi [kcoopermiller]! I realized that right after I committed the [dae9493]. loll
Thank you for double-checking the code!! I just uploaded [8623639] it now should have "count" attribute for both mmg servers and reducers. And the count is incremented/ updated in the awaitReducer and awaitMMG!

**Review by wadefagen — APPROVED** [review]
This is fantastic -- thank you so much!!! 🎉 

I made a small commit to remove some unnecessary comments of code you changed and it looks great.  Merging it in now! :)

**Comment by wadefagen** [comment]
fixes #20 
fixes #21

**Pull request merged**
